survey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveys.urls')),
]

surveys/urls.py
from django.urls import path, include
from django.http import HttpResponse

from .views import auth
from .views import survey


survey_patterns = [
    path('create/', survey.create_survey, name='create-survey'),
    path('preview/<slug:slug>/', survey.preview_survey, name='preview-survey'),
    path('edit/<slug:slug>/', survey.edit_survey, name='edit-survey'),
    path('detail/<slug:slug>/', survey.details_survey, name='details-survey'),
    path('start/<slug:slug>/', survey.start_survey, name='start-survey'),
]

urlpatterns = [
    path('signup/', auth.signup, name='signup'),
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('survey/', include(survey_patterns)),
    path('surveys/', survey.survey_list, name='list-surveys'),
    path('thanks/<str:survey_title>', survey.ThankSubmission.as_view(), name='thanks-survey'),
    path('<slug:slug>/', survey.survey_submission, name='submission-survey'),
]

surveys/models/answer.py
from django.db import models
from .option import Option
from .submission import Submission


class Answer(models.Model):
    submission = models.ForeignKey(
        Submission,
        on_delete=models.CASCADE
    )
    option = models.ForeignKey(
        Option,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

surveys/models/option.py
from django.db import models
from .question import Question
from .submission import Submission


class Option(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE
    )
    text = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)

    def rate(self):
        total_submissions = Submission.objects.filter(
            survey__question__option=self).count()
        option_submissions = Submission.objects.filter(
            survey__question__option=self, answer__option=self).count()
        
        if total_submissions > 0:
            return (option_submissions / total_submissions) * 100
        else:
            return 0

surveys/models/question.py
from django.db import models
from .survey import Survey


class Question(models.Model):
    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE
    )
    text = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)

surveys/models/submission.py
from django.db import models
from .survey import Survey


class Submission(models.Model):
    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE
    )
    submited_at = models.DateTimeField(auto_now_add=True)

surveys/models/survey.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.utils.text import slugify


class Survey(models.Model):
    creator = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    slug = models.SlugField(max_length=100, unique=True)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not len(self.slug.strip()):
            self.slug = slugify(self.title)

        _slug = self.slug
        _count = 1

        while True:
            try:
                Survey.objects.all().exclude(pk=self.pk).get(slug=_slug)
            except MultipleObjectsReturned:
                pass
            except ObjectDoesNotExist:
                break
            _slug = "%s-%s" % (self.slug, _count)
            _count += 1

        self.slug = _slug

        super(Survey, self).save(*args, **kwargs)

    def total_submissions(self):
        return self.submission_set.count()

    def status(self):
        if self.is_active:
            return 'Running'
        else:
            return 'Not Active'

surveys/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import TemplateView
from .forms import SurveyForm, QuestionFormSet
from .models import Survey


@login_required
def create_survey(request):
    survey = Survey()
    if request.method == 'POST':
        survey.creator = request.user
        survey_form = SurveyForm(request.POST, instance=survey)
        question_formset = QuestionFormSet(
            request.POST, instance=survey)

        if all([survey_form.is_valid(), question_formset.is_valid()]):
            survey_form.save()
            question_formset.save()
            return HttpResponseRedirect(reverse(
                'preview-survey', kwargs={ 'slug': survey.slug }))
    else:
        survey_form = SurveyForm(instance=survey)
        question_formset = QuestionFormSet(instance=survey)

    context = {
        'formSurvey': survey_form,
        'formQuestion': question_formset,
    }

    return render(request, 'surveys/pages/create.html', context)

@login_required
def preview_survey(request, slug):
    survey = get_object_or_404(Survey, slug=slug, creator=request.user)

    if survey.is_active:
        return HttpResponseRedirect(reverse(
            'details-survey', kwargs={ 'slug': survey.slug }))

    context = {
        'survey': survey,
    }
    return render(request, 'surveys/pages/preview.html', context)

surveys/views/survey.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import transaction
from django.forms import formset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from ..forms import (AnswerForm, BaseAnswerFormSet, EditQuestionFormSet, 
    StatusFilter, SortFilter, SurveyForm, QuestionFormSet)
from ..models import Answer, Submission, Survey, Question


@login_required
def create_survey(request):
    survey = Survey()
    if request.method == 'POST':
        survey.creator = request.user
        survey_form = SurveyForm(request.POST, instance=survey)
        question_formset = QuestionFormSet(
            request.POST, instance=survey)

        if all([survey_form.is_valid(), question_formset.is_valid()]):
            survey_form.save()
            question_formset.save()
            return redirect('preview-survey', slug=survey.slug)
    else:
        survey_form = SurveyForm(instance=survey)
        question_formset = QuestionFormSet(instance=survey)

    context = {
        'formSurvey': survey_form,
        'formQuestion': question_formset,
    }

    return render(request, 'surveys/pages/create.html', context)

@login_required
def preview_survey(request, slug):
    survey = get_object_or_404(Survey, slug=slug, creator=request.user)

    if survey.is_active:
        return redirect('details-survey', slug=survey.slug)

    context = {
        'survey': survey,
    }
    return render(request, 'surveys/pages/preview.html', context)

@login_required
def edit_survey(request, slug):
    survey = get_object_or_404(Survey, slug=slug, creator=request.user)

    if survey.is_active:
        return redirect('details-survey', slug=survey.slug)

    if request.method == 'POST':
        survey_form = SurveyForm(request.POST or None, instance=survey)
        question_formset = EditQuestionFormSet(
            request.POST or None, instance=survey,
            queryset=Question.objects.filter(survey=survey).order_by('id'))

        if all([survey_form.is_valid(), question_formset.is_valid()]):
            survey_form.save()
            question_formset.save()
            return redirect('preview-survey', slug=survey.slug)
    else:
        survey_form = SurveyForm(instance=survey)
        question_formset = EditQuestionFormSet(
            instance=survey,
            queryset=Question.objects.filter(survey=survey).order_by('id'))

    context = {
        'survey': survey,
        'formSurvey': survey_form,
        'formQuestion': question_formset,
    }

    return render(request, 'surveys/pages/edit.html', context)

@login_required
def details_survey(request, slug):
    survey = get_object_or_404(Survey, slug=slug, creator=request.user)

    if not survey.is_active:
        return redirect('preview-survey', slug=survey.slug)

    total_submissions = Submission.objects.filter(survey=survey).count()
    host = request.get_host()
    public_path = reverse('submission-survey', kwargs={ 'slug': survey.slug })
    public_url = f'{request.scheme}://{host}{public_path}'
    context = {
        'public_url': public_url,
        'survey': survey,
        'total_submissions': total_submissions,
    }
    return render(request, 'surveys/pages/detail.html', context)

@login_required
def start_survey(request, slug):
    survey = get_object_or_404(Survey, slug=slug, creator=request.user)

    if not survey.is_active:
        survey.is_active = True
        survey.save()
        return redirect('details-survey', slug=survey.slug)

    return redirect('preview-survey', slug=survey.slug)

@login_required
def survey_list(request):
    statuses = StatusFilter(request.GET)
    sorting = SortFilter(request.GET)

    request_status = request.GET.get('status')
    request_sorting = request.GET.get('sort')
    request_search = request.GET.get('search')
    
    surveys = Survey.objects.filter(creator=request.user)

    if request_status == 'all' or not request_status:
        surveys = surveys.order_by('-created_at')
    elif request_status == 'running':
        surveys = surveys.filter(is_active=True).order_by('-created_at')
    elif request_status == 'inactive':
        surveys = surveys.filter(is_active=False).order_by('-created_at')

    if request_sorting == 'newest':
        surveys = surveys.order_by('-created_at')
    elif request_sorting == 'oldest':
        surveys = surveys.order_by('created_at')

    if request_search:
        surveys = surveys.filter(title__icontains=request_search)

    paginator = Paginator(surveys, 10)

    page_number = request.GET.get('page')
    survey_page = paginator.get_page(page_number)

    context = {
        'surveys': survey_page,
        'statuses': statuses,
        'sorting': sorting,
    }
    return render(request, 'surveys/pages/surveys-list.html', context)

def survey_submission(request, slug):
    survey = get_object_or_404(Survey, slug=slug, is_active=True)
    questions = survey.question_set.order_by('id')

    form_kwargs = { 'questions': questions }

    AnswerFormSet = formset_factory(AnswerForm, extra=len(questions), formset=BaseAnswerFormSet)
    if request.method == 'POST':
        question_formset = AnswerFormSet(request.POST, form_kwargs=form_kwargs)
        if question_formset.is_valid():
            with transaction.atomic():
                submission = Submission.objects.create(survey=survey)
                for question in question_formset:
                    Answer.objects.create(
                        option_id=question.cleaned_data['option'], submission=submission)
            
            return redirect('thanks-survey', permanent=True, survey_title=survey.title)
    else:
        question_formset = AnswerFormSet(form_kwargs=form_kwargs)
        
    context = {
        'survey': survey,
        'questions': question_formset,
    }
    return render(request, 'surveys/pages/submission.html', context)

class ThankSubmission(TemplateView):
    template_name = 'surveys/pages/thanks-submission.html'
    permanent = True

surveys/templates/surveys/pages/create.html
{% extends '../base.html' %}

{% block page-styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/survey/css/survey.css' %}">
    <link rel="stylesheet" href="{% static '/survey/css/create.css' %}">
{% endblock page-styles %}

{% block page-title %}
    Create Survey
{% endblock page-title %}

{% block page-actions %}
    <button x-data="actions" @click="createSurveySubmit" type="button" class="action-btn">Create Survey</button>
{% endblock page-actions %}

{% block page-content %}
    <form action="{% url 'create-survey' %}" method="post" id="create-survey-form">
        {% csrf_token %}
        <div x-data="form" class="survey-details">
            <div class="form-group">
                {% for field in formSurvey %}
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                {% endfor %}
            </div>
            <div class="divider-form"><div></div></div>
            <div x-ref="questions-container" class="questions-container">
                <div class="hidden">
                    {% with empty_question=formQuestion.empty_form %}
                    <div x-ref="question-form-container" class="question-form-container placeholder">
                        <button class="btn-delete-question" @click="deleteQuestion" type="button">
                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </button>
                        <div class="form-group">
                            {{ empty_question }}
                        </div>
                        <div class="form-group">
                            <label>Options</label>
                            <ul class="options-list">
                                {{ empty_question.options.management_form }}
                                {% with empty_option=empty_question.options.empty_form %}
                                <li class="option-item" x-ref="option-item">
                                    <div class="option-container">
                                        {{ empty_option }}
                                        <button @click="deleteOption" type="button">
                                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                        </button>
                                    </div>
                                </li>
                                {% endwith %}
                            </ul>
                            <button @click="addOption" type="button" class="action-btn">Add Option</button>
                        </div>
                    </div>
                    {% endwith %}
                </div>
                {{ formQuestion.management_form }}
                {% for question in formQuestion.forms %}
                    <div class="question-form-container">
                        <button class="btn-delete-question" @click="deleteQuestion" type="button">
                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </button>
                        <div class="form-group">
                            {{ question.text.label_tag }}
                            {{ question.text }}
                            {{ question.text.errors }}
                        </div>
                        <div class="form-group">
                            <label>Options</label>
                            <ul class="options-list">
                                {{ question.options.management_form }}
                                {% for option in question.options.forms %}
                                    <li class="option-item">
                                        <div class="option-container">
                                            {{ option.text }}
                                            <button @click="deleteOption" type="button">
                                                <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                </svg>
                                            </button>
                                        </div>
                                        <ul class="errorlist">
                                        {% for error in option.text.errors %}
                                            <li>{{ error }}</>
                                        {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                            <button @click="addOption" type="button" class="action-btn">Add Option</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button @click="addQuestion" type="button" class="action-btn">Add Question</button>
        </div>
    </form>
{% endblock page-content %}

{% block page-javascript %}
    <script src="{% static 'surveys/js/create.js' %}" type="text/javascript"></script>
{% endblock page-javascript %}

surveys/templates/surveys/pages/detail.html
{% extends '../base.html' %}

{% block page-styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/survey/css/survey.css' %}">
    <link rel="stylesheet" href="{% static '/survey/css/preview.css' %}">
{% endblock page-styles %}

{% block page-title %}
    Survey Details
{% endblock page-title %}

{% block page-actions %}
    <a href="{% url 'list-surveys' %}" class="action-btn">View Surveys</a>
{% endblock page-actions %}

{% block page-content %}
        <div x-data="clipboard" class="survey-details">
            <div class="form-group">
                <p class="field survey-title">{{ survey.title }}</p>
                <p class="field survey-description">{{ survey.description }}</p>
                <p class="field survey-description">You have had 
                    <span class="font-bold">{{ total_submissions }} submission{{ total_submissions|pluralize }}</span>
                </p>
                <div class="url-container">
                    <span x-cloak x-show="isCopied"
                        x-transition.scale.origin.bottom
                        class="tooltip-container">
                        <span class="tooltip-icon">
                            <svg aria-hidden="true" width="16" height="6" viewBox="0 0 16 6" class="absolute left-1/2 top-full -ml-2 -mt-px text-gray-900"><path fill-rule="evenodd" clip-rule="evenodd" d="M15 0H1V1.00366V1.00366V1.00371H1.01672C2.72058 1.0147 4.24225 2.74704 5.42685 4.72928C6.42941 6.40691 9.57154 6.4069 10.5741 4.72926C11.7587 2.74703 13.2803 1.0147 14.9841 1.00371H15V0Z" fill="currentColor"></path></svg>
                            Copied!
                        </span>
                    </span>
                    <p @click="copyToClipboard" class="field survey-description">Survey URL: <span x-ref="url" class="url-copy">{{ public_url }}</span></p>
                </div>
            </div>
            <div class="divider-form"><div></div></div>
            <div class="questions-container">
                <p class="field survey-title">Results</p>
                {% for question in survey.question_set.all %}
                    <div class="question-form-container">
                        <div class="form-group">
                            <p class="field field-question">{{ question.text }}</p>
                        </div>
                        <div class="form-group">
                            <ol class="options-list">
                                {% for option in question.option_set.all %}
                                    <li class="option-item">
                                        <p class="field"> {{ option.text }} - {{ option.rate|floatformat:2 }}% </p>
                                    </li>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
{% endblock page-content %}

{% block page-javascript %}
    <script src="{% static 'surveys/js/detail.js' %}" type="text/javascript"></script>
{% endblock page-javascript %}

surveys/templates/surveys/pages/edit.html
{% extends '../base.html' %}

{% block page-styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/survey/css/survey.css' %}">
    <link rel="stylesheet" href="{% static '/survey/css/survey-form.css' %}">
{% endblock page-styles %}

{% block page-title %}
    Edit Survey
{% endblock page-title %}

{% block page-actions %}
    <button x-data="actions" @click="editSurveySubmit" type="button" class="action-btn">Save Survey</button>
{% endblock page-actions %}

{% block page-content %}
    <form action="{% url 'edit-survey' survey.slug %}" method="post" id="edit-survey-form">
        {% csrf_token %}
        <div x-data="form" class="survey-details">
            <div class="form-group">
                {% for field in formSurvey %}
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                {% endfor %}
            </div>
            <div class="divider-form"><div></div></div>
            <div x-ref="questions-container" class="questions-container">
                <div class="hidden">
                    {% with empty_question=formQuestion.empty_form %}
                    <div x-ref="question-form-container" class="question-form-container placeholder">
                        <button class="btn-delete-question" @click.stop="deleteQuestion" type="button">
                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </button>
                        <div class="form-group">
                            {{ empty_question.text.label_tag }}
                            {{ empty_question.text }}
                            {{ empty_question.text.errors }}
                        </div>
                        <div class="form-group">
                            <label>Options</label>
                            <ul class="options-list">
                                {{ empty_question.options.management_form }}
                                {% with empty_option=empty_question.options.empty_form %}
                                <li class="option-item" x-ref="option-item">
                                    <div class="option-container">
                                        {{ empty_option.text }}
                                        <button @click.stop="deleteOption" type="button">
                                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                        </button>
                                    </div>
                                </li>
                                {% endwith %}
                            </ul>
                            <button @click="addOption" type="button" class="action-btn">Add Option</button>
                        </div>
                    </div>
                    {% endwith %}
                </div>
                {{ formQuestion.management_form }}
                {% for question in formQuestion.forms %}
                    <div class="question-form-container">
                        <button class="btn-delete-question" @click.stop="deleteQuestion" type="button">
                            {{ question.DELETE }}
                            <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </button>
                        <div class="form-group">
                            {{ question.id }}
                            {{ question.text.label_tag }}
                            {{ question.text }}
                            {{ question.text.errors }}
                        </div>
                        <div class="form-group">
                            <label>Options</label>
                            <ul class="options-list">
                                {{ question.options.management_form }}
                                {% for option in question.options.forms %}
                                    <li class="option-item">
                                        <div class="option-container">
                                            {{ option.id }}
                                            {{ option.text }}
                                            <button class="btn-delete-option" @click.stop="deleteOption" type="button">
                                                {{ option.DELETE }}
                                                <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                </svg>
                                            </button>
                                        </div>
                                        <ul class="errorlist">
                                        {% for error in option.text.errors %}
                                            <li>{{ error }}</>
                                        {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                            <button @click="addOption" type="button" class="action-btn">Add Option</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button @click="addQuestion" type="button" class="action-btn">Add Question</button>
        </div>
    </form>
{% endblock page-content %}

{% block page-javascript %}
    <script src="{% static 'surveys/js/dynamic-survey-form.js' %}" type="text/javascript"></script>
    <script src="{% static 'surveys/js/edit.js' %}" type="text/javascript"></script>
{% endblock page-javascript %}

surveys/templates/surveys/pages/preview.html
{% extends '../base.html' %}

{% block page-styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/survey/css/survey.css' %}">
    <link rel="stylesheet" href="{% static '/survey/css/preview.css' %}">
{% endblock page-styles %}

{% block page-title %}
    Preview Survey
{% endblock page-title %}

{% block page-actions %}
    <a href="{% url 'edit-survey' survey.slug %}" class="action-btn">Edit Survey</a>
    <a href="{% url 'start-survey' survey.slug %}" class="action-btn">Start Survey</a>
{% endblock page-actions %}

{% block page-content %}
    <div class="survey-details">
        <div class="form-group">
            <p class="field-title">Survey title:</p>
            <p class="field">{{ survey.title }}</p>
            <p class="field-title">Description:</p>
            <p class="field text-justify">{{ survey.description }}</p>
        </div>
        <div class="divider-form"><div></div></div>
        <div class="questions-container">
            {% for question in survey.question_set.all %}
                <div class="question-form-container">
                    <div class="form-group">
                        <p class="field-title">Question:</p>
                        <p class="field field-question">{{ question.text }}</p>
                    </div>
                    <div class="form-group">
                        <p class="field-title">Options</p>
                        <ul class="options-list">
                            {% for option in question.option_set.all %}
                                <li class="option-item">
                                    <p class="field"> {{ option.text }} </p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock page-content %}

{% block page-javascript %}
    <script src="{% static 'surveys/js/create.js' %}" type="text/javascript"></script>
{% endblock page-javascript %}

surveys/templates/surveys/pages/thanks-submission.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Surveys</title>

        {% load static %}
        <link rel="stylesheet" href="{% static '/survey/css/tailwind.css' %}">
        <link rel="stylesheet" href="{% static '/survey/css/base.css' %}">
        <link rel="stylesheet" href="{% static '/survey/css/thanks-submission.css' %}">
    </head>
    <body>
        <header>
            <div class="header-nav">
                <a href="#">
                    <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="brand-icon">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                    </svg>
                </a>

                <h1>Surveys</h1>

                <div>
                </div>
            </div>
            <div class="divider-header"><div></div></div>
        </header>

        <main>
            <h3>Thanks! All done.</h3>
            <p>Thanks for taking <span class="survey-title">{{ survey_title }}</span>.</p>
            <p>You can close this page now.</p>
        </main>

        <script src="{% static 'survey/js/alpine.min.js' %}" type="module"></script>
    </body>
</html>